version: "2"
services:
  app:
    container_name: bookshelf-server
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: on-failure
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"